version: "3.9"

x-aws-vpc: "vpc-0f1c47f4589e227d5"

services:
  security:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_backend_security_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
      - DB_ACCESS_URI="sqlite:///database.db"
    ports:
      - "5050:5050"

  bookings:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_backend_bookings_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
      - DB_ACCESS_URI="sqlite:///database.db"
    ports:
      - "5010:5010"

  flights:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_backend_flights_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
      - DB_ACCESS_URI="sqlite:///database.db"
    ports:
      - "5020:5020"

  users:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_backend_users_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
      - DB_ACCESS_URI="sqlite:///database.db"
    ports:
      - "5030:5030"

  data_prod:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_backend_data_producers_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
      - DB_ACCESS_URI="sqlite:///database.db"
    ports:
      - "5040:5040"

  admin:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/utopia_frontend_admin_microservice-sh
    environment:
      - SECRET_KEY="This:Is:A:Bad:Secret:Key:Bro!"
    ports:
      - "5000:5000"
